version: "3.9"
services:
  web:
    image: nginx
    build: ./public/
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
      - ./public/nginx.conf:/etc/nginx/conf.d/default.conf